/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TenantsImport } from './routes/tenants'
import { Route as HousingImport } from './routes/housing'
import { Route as CalendarImport } from './routes/calendar'
import { Route as AuthenticatedImport } from './routes/_authenticated'

// Create/Update Routes

const TenantsRoute = TenantsImport.update({
  path: '/tenants',
  getParentRoute: () => rootRoute,
} as any)

const HousingRoute = HousingImport.update({
  path: '/housing',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarImport.update({
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      preLoaderRoute: typeof CalendarImport
      parentRoute: typeof rootRoute
    }
    '/housing': {
      preLoaderRoute: typeof HousingImport
      parentRoute: typeof rootRoute
    }
    '/tenants': {
      preLoaderRoute: typeof TenantsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute,
  CalendarRoute,
  HousingRoute,
  TenantsRoute,
])

/* prettier-ignore-end */
